# Generated by Django 5.2.18 on 2026-10-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.TextField(blank=True, null=True, verbose_name='Nome completo')),
                ('nif', models.TextField(blank=True, null=True, unique=True, verbose_name='NIF')),
                ('niss', models.TextField(blank=True, null=True, unique=True, verbose_name='NISS')),
                ('passaporte', models.TextField(blank=True, null=True, unique=True, verbose_name='Passaporte')),
                ('titulo_residencia', models.TextField(blank=True, db_column='bi_cc_titulo_residência', null=True, unique=True, verbose_name='BI / CC / título de residência')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('genero', models.TextField(blank=True, db_column='gênero', null=True, verbose_name='Género')),
                ('estado_civil', models.TextField(blank=True, null=True, verbose_name='Estado civil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ddi', models.BigIntegerField(blank=True, null=True, verbose_name='Indicativo telefónico')),
                ('contato', models.TextField(blank=True, null=True, verbose_name='Telefone')),
                ('rua', models.TextField(blank=True, null=True, verbose_name='Rua')),
                ('numero_rua', models.TextField(blank=True, null=True, verbose_name='Número')),
                ('complemento', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('localidade', models.TextField(blank=True, null=True, verbose_name='Localidade')),
                ('codigo_postal', models.TextField(blank=True, db_column='código_postal', null=True, verbose_name='Código postal')),
                ('profissao', models.TextField(blank=True, db_column='profissão', null=True, verbose_name='Profissão')),
                ('nacionalidade', models.TextField(blank=True, null=True, verbose_name='Nacionalidade')),
                ('naturalidade', models.TextField(blank=True, null=True, verbose_name='Naturalidade')),
                ('validade_passaporte', models.DateField(blank=True, null=True, verbose_name='Validade do passaporte')),
                ('emissao_passaporte', models.DateField(blank=True, db_column='emissão_passaporte', null=True, verbose_name='Emissão do passaporte')),
                ('local_emissao_passaporte', models.TextField(blank=True, db_column='local_emissão_passaporte', null=True, verbose_name='Local de emissão')),
                ('validade_bi_cc', models.DateField(blank=True, null=True, verbose_name='Validade do BI / CC')),
                ('emissao_bi_cc', models.DateField(blank=True, db_column='emissão_bi_cc', null=True, verbose_name='Emissão do BI / CC')),
                ('notas_documento', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'cliente',
                'ordering': ['nome_completo', 'cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('entidade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidade', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Entidade',
                'db_table': 'entidade',
                'ordering': ['entidade'],
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('fase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fase', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fase de processo',
                'verbose_name_plural': 'Fases de processo',
                'db_table': 'lista_fases_processo',
                'ordering': ['fase'],
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('motivo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Motivo de pagamento',
                'verbose_name_plural': 'Motivos de pagamento',
                'db_table': 'motivo',
                'ordering': ['motivo'],
            },
        ),
        migrations.CreateModel(
            name='StatusPagamento',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado de pagamento',
                'verbose_name_plural': 'Estados de pagamento',
                'db_table': 'status_pagamento',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('tipo_do_processo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_do_processo', models.TextField(verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de processo',
                'verbose_name_plural': 'Tipos de processo',
                'db_table': 'tipo_do_processo',
                'ordering': ['tipo_do_processo'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('evento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de início')),
                ('duracao', models.TextField(blank=True, null=True, verbose_name='Duração')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('google_event_id', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='office.cliente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'db_table': 'agendamento',
                'ordering': ['data_inicio', 'evento_id'],
                'permissions': [('sync_calendar', 'Pode sincronizar a agenda Google')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento_nome', models.TextField(verbose_name='Documento')),
                ('entregue', models.BooleanField(blank=True, default=False, null=True, verbose_name='Entregue')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='office.cliente')),
            ],
            options={
                'verbose_name': 'Documento do cliente',
                'verbose_name_plural': 'Documentos do cliente',
                'db_table': 'documentos_cliente',
                'ordering': ['documento_nome'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('processo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('juiz', models.TextField(blank=True, null=True, verbose_name='Juiz')),
                ('numero_processo', models.TextField(blank=True, null=True, unique=True, verbose_name='Número do processo')),
                ('processo_anexo_principal', models.TextField(blank=True, null=True, verbose_name='Referência do anexo principal')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='office.cliente')),
                ('entidade', models.ForeignKey(blank=True, db_column='entidade_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='office.entidade')),
                ('tipo', models.ForeignKey(blank=True, db_column='tipo_do_processo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='office.tipoprocesso')),
            ],
            options={
                'verbose_name': 'Processo',
                'db_table': 'processo',
                'ordering': ['-processo_id'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('etapa_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_fase', models.DateField(blank=True, null=True, verbose_name='Data da fase')),
                ('observacao', models.TextField(blank=True, db_column='observação', null=True, verbose_name='Observação')),
                ('fase', models.ForeignKey(blank=True, db_column='fase_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='office.fase')),
                ('processo', models.ForeignKey(db_column='processo_id', on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='office.processo')),
            ],
            options={
                'verbose_name': 'Etapa',
                'db_table': 'etapa_processo',
                'ordering': ['-data_fase', '-etapa_id'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('pagamento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidade', models.IntegerField(blank=True, null=True, verbose_name='Entidade de pagamento')),
                ('referencia', models.IntegerField(blank=True, null=True, verbose_name='Referência')),
                ('montante', models.FloatField(blank=True, null=True, verbose_name='Montante (€)')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data limite')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='office.cliente')),
                ('motivo', models.ForeignKey(blank=True, db_column='motivo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='office.motivo')),
                ('status', models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='office.statuspagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'db_table': 'pagamento',
                'ordering': ['data_limite', '-pagamento_id'],
            },
        ),
    ]
