# Generated by Django 5.2.18 on 2026-10-07 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('office', '0001_legacy_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='office', max_length=30, unique=True)),
                ('encrypted_credentials', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('file', models.FileField(upload_to='templates/%Y/%m/', verbose_name='Modelo DOCX')),
                ('required_fields', models.JSONField(default=list, verbose_name='Campos obrigatórios')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Modelo de documento',
                'verbose_name_plural': 'Modelos de documento',
                'ordering': ['name'],
                'permissions': [('generate_document', 'Pode gerar documentos')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de auditoria',
                'verbose_name_plural': 'Registos de auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('estado_civil', 'Estados civis'), ('genero', 'Géneros'), ('motivo_agenda', 'Motivos de agendamento'), ('duracao_agenda', 'Durações de agendamento'), ('documento', 'Documentos solicitados')], max_length=30, verbose_name='Categoria')),
                ('label', models.CharField(max_length=300, verbose_name='Nome')),
                ('minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minutos (para durações)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Opção configurável',
                'verbose_name_plural': 'Opções configuráveis',
                'ordering': ['order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('category', 'label'), name='unique_configuration_label')],
            },
        ),
    ]
