# Generated by Django 5.2.18 on 2026-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_database_catalogues'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='office', max_length=30, unique=True)),
                ('encrypted_credentials', models.TextField()),
                ('root_folder_id', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='drive_folder_id',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='drive_file_id',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='drive_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
