# Generated by Django 5.2.18 on 2026-10-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_driveconnection_cliente_drive_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='numero_parcela',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Parcela'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='plano_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='total_parcelas',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
